[colors.primary]
background = "#1e1b16"
foreground = "#e9d8c3"

[colors.cursor]
text = "#1e1b16"
cursor = "#c47f17"

[colors.selection]
text = "#1e1b16"
background = "#c47f17"

[colors.normal]
black = "#15120e"
red = "#a9432d"
green = "#8a9a5b"
yellow = "#d9a441"
blue = "#5a6c6e"
magenta = "#755c71"
cyan = "#cb7723"
white = "#f5eee6"

[colors.bright]
black = "#15120e"
red = "#a9432d"
green = "#8a9a5b"
yellow = "#d9a441"
blue = "#5a6c6e"
magenta = "#755c71"
cyan = "#cb7723"
white = "#f5eee6"
